export type { ContainerProps } from '@/interfaces/Container'
export type { PillProps } from '@/interfaces/Pill'
export type { AboutProps } from '@/interfaces/About'
export type * from '@/interfaces/Card'
export type * from '@/interfaces/Avatar'